Algoritmo "Teste_1_capgemini"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme Araújo
// Data atual  : 20/02/2022
Var
   n,i,j: inteiro


Inicio
      escreva("Digite a altura da escada: ")
      leia(n)
      
      para i de 1 ate n faca
           escreval
      para j de 1 ate i faca
           escreva("*")
      fimpara
      fimpara
      


Fimalgoritmo